replicaCount: 1

images:
  API:
    repository: hseling/hseling-api-template
    tag: latest
    pullPolicy: Always
  Web:
    repository: hseling/hseling-web-template
    tag: latest
    pullPolicy: Always
  WebDB:
    # repository: ""
    repository: hseling/hseling-web-template
    tag: db
    pullPolicy: Always
  Mysql:
    # repository: ""
    repository: mysql
    tag: latest
    pullPolicy: Always
  Redis:
    # repository: ""
    repository: redis
    tag: latest
    pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: ""
      paths: ["/"]


  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

storageClass: ""
hostPath: ""

secrets:
  mysqlPassword: "aHNlbGluZy1wYXNzd29yZA=="
  postgresPassword: "aHNlbGluZy1wYXNzd29yZA=="

mountPath: /data
localPath: ""

storage:
  appSpace: 1Gi
  mysqlSpace: 50Gi
  redisSpace: 1Gi
