apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hseling.fullname" . }}-celery
  labels:
    app: celery
    app.kubernetes.io/name: {{ include "hseling.name" . }}-celery
    helm.sh/chart: {{ include "hseling.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hseling.name" . }}-celery
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "hseling.name" . }}-celery
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.images.API.repository }}:{{ .Values.images.API.tag }}"
          command: ["celery", "-A", "main.celery", "worker"]
          imagePullPolicy: {{ .Values.images.API.pullPolicy }}
          envFrom:
          - secretRef:
              name: {{ include "hseling.name" . }}-secret
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.storageClass }}
          volumeMounts:
            - name: {{ include "hseling.name" . }}-deployment-volume
              mountPath: {{ .Values.mountPath }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if .Values.storageClass }}
      volumes:
        - name: {{ include "hseling.name" . }}-deployment-volume
          persistentVolumeClaim:
            claimName: {{ include "hseling.name" . }}-pvc
    {{- end }}
