apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hseling.fullname" . }}-web
  labels:
    app: web
    app.kubernetes.io/name: {{ include "hseling.name" . }}-web
    helm.sh/chart: {{ include "hseling.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hseling.name" . }}-web
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "hseling.name" . }}-web
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.images.Web.repository }}:{{ .Values.images.Web.tag }}"
          imagePullPolicy: {{ .Values.images.Web.pullPolicy }}
          envFrom:
          - secretRef:
              name: {{ include "hseling.name" . }}-secret
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /web/
              port: http
          readinessProbe:
            httpGet:
              path: /web/
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
