apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hseling.name" . }}-pvc
  labels:
    app.kubernetes.io/name: {{ include "hseling.name" . }}
    helm.sh/chart: {{ include "hseling.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: {{ .Values.storageClass }}
