{{- if .Values.storageClass -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hseling.name" . }}-pvc
  labels:
    app.kubernetes.io/name: {{ include "hseling.name" . }}
    helm.sh/chart: {{ include "hseling.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.space }}
  storageClassName: {{ .Values.storageClass }}
{{- end }}
