{{- if .Values.storageClass -}}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hseling.name" . }}-app-pvc
  labels:
    app.kubernetes.io/name: {{ include "hseling.name" . }}
    helm.sh/chart: {{ include "hseling.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.appSpace }}
  storageClassName: {{ .Values.storageClass }}
---
{{- if .Values.images.Mysql.repository }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hseling.name" . }}-mysql-pvc
  labels:
    app.kubernetes.io/name: {{ include "hseling.name" . }}
    helm.sh/chart: {{ include "hseling.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "2"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.mysqlSpace }}
  storageClassName: {{ .Values.storageClass }}
{{- end }}
---
{{- if .Values.images.Mysql.repository }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hseling.name" . }}-redis-pvc
  labels:
    app.kubernetes.io/name: {{ include "hseling.name" . }}
    helm.sh/chart: {{ include "hseling.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "3"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.redisSpace }}
  storageClassName: {{ .Values.storageClass }}
{{- end }}

{{- end }}
