apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hseling.name" . }}-secret
  labels:
    app.kubernetes.io/name: {{ include "hseling.name" . }}
    helm.sh/chart: {{ include "hseling.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  CELERY_BROKER_URL: {{ (printf "redis://%s-redis:6379" (include "hseling.fullname" .)) | b64enc }}
  CELERY_RESULT_BACKEND: {{ (printf "redis://%s-redis:6379" (include "hseling.fullname" .)) | b64enc }}
  MYSQL_HOST: {{ (printf "%s-mysql" (include "hseling.fullname" .)) | b64enc }}
  MYSQL_ROOT_PASSWORD: {{ .Values.secrets.mysqlPassword }}
  MYSQL_USER: bXlzcWwK
  MYSQL_PASSWORD: {{ .Values.secrets.mysqlPassword }}
  MYSQL_DATABASE: {{ (include "hseling.name" .) | trimSuffix "\n" | b64enc }}
  ALLOWED_HOSTS: Kg==
  DEBUG_MODE: MQ==
  HSELING_API_ROOT: {{ (printf "http://%s-api/" (include "hseling.fullname" .)) | b64enc }}
  POSTGRES_HOST: {{ (printf "%s-webdb" (include "hseling.fullname" .)) | b64enc }}
  POSTGRES_DB: aHNlbGluZw==
  POSTGRES_USER: aHNlbGluZw==
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword }}
  POSTGRES_PORT: NTQzMg==
  RESTRICTED_MODE: MAo=
