{{- if .Values.images.Mysql.repository }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hseling.fullname" . }}-mysql
  labels:
    app: mysql
    app.kubernetes.io/name: {{ include "hseling.name" . }}-mysql
    helm.sh/chart: {{ include "hseling.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: mysql
  selector:
    app.kubernetes.io/name: {{ include "hseling.name" . }}-mysql
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
