apiVersion: v1
kind: Service
metadata:
  name: {{ include "hseling.fullname" . }}-minio
  labels:
    app: minio
    app.kubernetes.io/name: {{ include "hseling.name" . }}-minio
    helm.sh/chart: {{ include "hseling.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "hseling.name" . }}-minio
    app.kubernetes.io/instance: {{ .Release.Name }}
