{{- if .Values.images.Redis.repository }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hseling.fullname" . }}-redis
  labels:
    app: redis
    app.kubernetes.io/name: {{ include "hseling.name" . }}-redis
    helm.sh/chart: {{ include "hseling.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/name: {{ include "hseling.name" . }}-redis
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
