{{- if .Values.images.WebDB.repository }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hseling.fullname" . }}-webdb
  labels:
    app.kubernetes.io/name: {{ include "hseling.name" . }}-webdb
    helm.sh/chart: {{ include "hseling.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app.kubernetes.io/name: {{ include "hseling.name" . }}-webdb
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
